cc_test(
  name = "binarytree-test",
  size = "small",
  srcs = ["binarytree-test.cc"],
  deps = ["@com_google_googletest//:gtest_main", "binarytree"],
)

cc_library(
    name = "binarytree",
    srcs = ["binarytree.cc"],
    hdrs = ["binarytree.h"],
)

